function Exception.throw 0
push argument 0
call Output.printString 1
pop temp 0
call Output.println 0
pop temp 0
push constant 42
call Sys.error 1
pop temp 0
push constant 0
return
